#ifndef MAIN_CONFIG_H_
#define MAIN_CONFIG_H_
#define NORMAL_SYSTEM_MODE 0
#define BLOCK_SYSTEM_MODE 1
#define PASSWORD_MATCH 2
#define PASSWORD_NOT_MATCH 3
#define PASSWORD_CHECK_REQUEST 4
#define DOOR_OPEN_REQUEST 5
#define PASSWORD_CREATE_MATCH 6
#define PASSWORD_CREATE_NOT_MATCH 7
#define PASSWORD_CREATE_REQUEST 8
#define FIRST_PASS_REQUEST 9
#define SECOND_PASS_REQUEST 10
#define BUZZER_REQUEST 11
#define NO_REQUEST 99
#define PASSWORD_ADDRESS 0x0311
#endif
